# MCUBoot
CONFIG_BOOTLOADER_MCUBOOT=y

# UART out
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

# UART thru USB
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_PID=0x0004
CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="USBD console sample"

# HW ID
CONFIG_HW_ID_LIBRARY=y

# GPIO
CONFIG_GPIO=y

# log
CONFIG_LOG=y
