# UART out
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

# UART thru USB
CONFIG_USB_DEVICE_STACK=y

# HW ID
CONFIG_HW_ID_LIBRARY=y

# GPIO
CONFIG_GPIO=y
CONFIG_GPIO_HOGS=y

# log
CONFIG_LOG=y
